services:
  db:
    image: postgres:15-alpine
    container_name: klucon-prime-db
    restart: always
    environment:
      - TZ=Europe/Prague
      - POSTGRES_USER=prime_user
      - POSTGRES_PASSWORD=prime_password
      - POSTGRES_DB=klucon_prime
    volumes:
      - /mnt/disk-a/klucon-prime/config/db_data:/var/lib/postgresql/data
    networks:
      - klucon_net

  klucon-prime:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.11
    container_name: klucon-prime
    restart: always
    depends_on:
      - db
    environment:
      - TZ=Europe/Prague
      - DB_URL=postgresql://prime_user:prime_password@db/klucon_prime
    ports:
      - "8000:80"
    volumes:
      - /mnt/disk-a/klucon-prime/app:/app
      - /mnt/disk-a/klucon-prime/templates:/app/templates
      - /mnt/disk-a/klucon-prime/lang:/app/lang
      - /mnt/disk-a/klucon-prime/config:/app/config
    command: >
      sh -c "pip install python-multipart passlib==1.7.4 bcrypt==4.0.1 sqlalchemy psycopg2-binary psutil distro && /start.sh"
    networks:
      - klucon_net

networks:
  klucon_net:
    driver: bridge
